### Dataset Import

In [47]:
#!pip install geopandas

In [48]:
import geopandas as gpd

################## TEST DATA ############
gdf = gpd.read_file('/Users/huss/data-processing/Github/GEO Project/Datasets/berlin-260625.osm.pbf')
print(gdf.head())

gdf2 = gpd.read_file('/Users/huss/data-processing/Github/GEO Project/Datasets/berlin-260625-free-2/berlin.gpkg')
print(gdf2.head())

################# CORRECT DATASET #############

df = gpd.read_file('/Users/huss/data-processing/Github/GEO Project/Datasets/berlin-260625-free/gis_osm_roads_free_1.shp')
print(df.head())

/opt/anaconda3/lib/python3.13/site-packages/pyogrio/geopandas.py:382: UserWarning: More than one layer found in 'berlin-260625.osm.pbf': 'points' (default), 'lines', 'multilinestrings', 'multipolygons', 'other_relations'. Specify layer parameter to avoid this warning.
  result = read_func(

   osm_id                    name barrier            highway   ref address  \
0  172544                    None    None           crossing  None    None
1  172548         Londoner Straße    None           bus_stop  None    None
2  458330              Kaiserdamm    None  motorway_junction     7    None
3  458350  Dreieck Charlottenburg    None  motorway_junction     4    None
4  458356        Dreieck Funkturm    None  motorway_junction     1    None

  is_in place man_made                                         other_tags  \
0  None  None     None  "crossing"=>"marked","crossing:island"=>"yes",...
1  None  None     None  "bench"=>"yes","bin"=>"yes","bus"=>"yes","chec...
2  None  None     None                        "destination"=>"Kaiserdamm"
3  None  None     None  "destination"=>"Hamburg;Reinickendorf;Siemensd...
4  None  None     None                                               None

                    geometry
0  POINT (13.34323 52.56662)
1  POINT (13.34229 52.56352)
2  POINT (13.28622 52.51156)
3  POINT (13.28664 52.53217)
4  POINT (13.26602 52.49335)

/opt/anaconda3/lib/python3.13/site-packages/pyogrio/geopandas.py:382: UserWarning: More than one layer found in 'berlin.gpkg': 'gis_osm_traffic_free' (default), 'gis_osm_transport_free', 'gis_osm_pois_free', 'gis_osm_places_free', 'gis_osm_natural_free', 'gis_osm_pofw_free', 'gis_osm_waterways_free', 'gis_osm_roads_free', 'gis_osm_railways_free', 'gis_osm_water_a_free', 'gis_osm_pois_a_free', 'gis_osm_landuse_a_free', 'gis_osm_buildings_a_free', 'gis_osm_traffic_a_free', 'gis_osm_protected_areas_a_free', 'gis_osm_pofw_a_free', 'gis_osm_natural_a_free', 'gis_osm_transport_a_free', 'gis_osm_places_a_free', 'gis_osm_adminareas_a_free'. Specify layer parameter to avoid this warning.
  result = read_func(

   osm_id  code               fclass                    name calming  \
0  172544  5204  pedestrian_crossing
1  458330  5206    motorway_junction              Kaiserdamm
2  458350  5206    motorway_junction  Dreieck Charlottenburg
3  458356  5206    motorway_junction        Dreieck Funkturm
4  484082  5206    motorway_junction        Saatwinkler Damm

                    geometry
0  POINT (13.34323 52.56662)
1  POINT (13.28622 52.51156)
2  POINT (13.28664 52.53217)
3  POINT (13.26602 52.49335)
4  POINT (13.29948 52.54652)
    osm_id  code       fclass                  name      ref oneway  maxspeed  \
0  4045150  5122  residential            Waldstraße     None      B        50
1  4045194  5122  residential  Ursula-Goetze-Straße     None      B        30
2  4045220  5122  residential        Hönower Straße     None      B        30
3  4045223  5122  residential   Gundelfinger Straße     None      F        30
4  4045243  5113      primary     Frankfurter Allee  B 1;B 5      F        50

   layer bridge tunnel                                           geometry
0      0      F      F  LINESTRING (13.60932 52.37462, 13.60936 52.374...
1      0      F      F  LINESTRING (13.53136 52.49263, 13.53136 52.492...
2      0      F      F  LINESTRING (13.52667 52.48948, 13.52639 52.489...
3      0      F      F  LINESTRING (13.52477 52.48558, 13.52484 52.485...
4      0      F      F  LINESTRING (13.4542 52.51571, 13.45431 52.5157...

### DATA INSPECTION

In [49]:
print("Shape:", gdf.shape)
print("\nColumn names:\n", gdf.columns.tolist())
print("\nData types:\n", gdf.dtypes)
print("\n", "Null Values:","\n", gdf.isna().sum())

Shape: (1171167, 11)

Column names:
 ['osm_id', 'name', 'barrier', 'highway', 'ref', 'address', 'is_in', 'place', 'man_made', 'other_tags', 'geometry']

Data types:
 osm_id          object
name            object
barrier         object
highway         object
ref             object
address         object
is_in           object
place           object
man_made        object
other_tags      object
geometry      geometry
dtype: object

 Null Values:
 osm_id              0
name          1091551
barrier       1041335
highway       1009817
ref           1132698
address       1171167
is_in         1171150
place         1170330
man_made      1144463
other_tags     109840
geometry            0
dtype: int64

In [50]:
print("Shape2:", gdf2.shape)
print("\nColumn names2:\n", gdf2.columns.tolist())
print("\nData types2:\n", gdf2.dtypes)
print("\n", "Null Values2:","\n", gdf2.isna().sum())

Shape2: (169791, 6)

Column names2:
 ['osm_id', 'code', 'fclass', 'name', 'calming', 'geometry']

Data types2:
 osm_id        object
code           int32
fclass        object
name          object
calming       object
geometry    geometry
dtype: object

 Null Values2:
 osm_id      0
code        0
fclass      0
name        0
calming     0
geometry    0
dtype: int64

In [51]:
print("Shape:", df.shape)
print("\nColumn names:\n", df.columns.tolist())
print("\nData types:\n", df.dtypes)
print("\n", "Null Values:","\n", df.isna().sum())

Shape: (460171, 11)

Column names:
 ['osm_id', 'code', 'fclass', 'name', 'ref', 'oneway', 'maxspeed', 'layer', 'bridge', 'tunnel', 'geometry']

Data types:
 osm_id        object
code           int32
fclass        object
name          object
ref           object
oneway        object
maxspeed       int32
layer          int64
bridge        object
tunnel        object
geometry    geometry
dtype: object

 Null Values:
 osm_id           0
code             0
fclass           0
name        357609
ref         455234
oneway           0
maxspeed         0
layer            0
bridge           0
tunnel           0
geometry         0
dtype: int64

In [52]:
gdf2.head(10000)

,osm_id,code,fclass,name,calming,geometry
0,172544,5204,pedestrian_crossing,,,POINT (13.34323 52.56662)
1,458330,5206,motorway_junction,Kaiserdamm,,POINT (13.28622 52.51156)
2,458350,5206,motorway_junction,Dreieck Charlottenburg,,POINT (13.28664 52.53217)
3,458356,5206,motorway_junction,Dreieck Funkturm,,POINT (13.26602 52.49335)
4,484082,5206,motorway_junction,Saatwinkler Damm,,POINT (13.29948 52.54652)
...,...,...,...,...,...,...
9995,1965563757,5201,traffic_signals,,,POINT (13.58651 52.44054)
9996,1965563833,5201,traffic_signals,,,POINT (13.58627 52.44085)
9997,1965563951,5204,pedestrian_crossing,,,POINT (13.5868 52.44097)
9998,1965563960,5201,traffic_signals,,,POINT (13.59331 52.44116)
9999,1965563969,5204,pedestrian_crossing,,,POINT (13.59313 52.4413)

In [53]:
gdf["name"] = gdf["name"].dropna()

In [54]:
gdf = gdf.dropna(subset=["name"])

In [55]:
print("\n", "Null Values:","\n", gdf.isna().sum())

 Null Values:
 osm_id            0
name              0
barrier       79416
highway       72934
ref           78073
address       79616
is_in         79606
place         78785
man_made      79254
other_tags      856
geometry          0
dtype: int64

In [56]:
gdf.tail(100)

,osm_id,name,barrier,highway,ref,address,is_in,place,man_made,other_tags,geometry
1170642,13956328201,Rentboks,None,None,None,None,None,None,None,"""shop""=>""hifi"",""website""=>""https://www.rentbok...",POINT (13.30549 52.53208)
1170647,13957074479,Grenzzone - Zonengrenze,None,None,None,None,None,None,None,"""description""=>""Eine Infotafel und drei Tafeln...",POINT (13.13257 52.39308)
1170651,13957201879,Referenzfläche,None,None,None,None,None,None,None,"""board_type""=>""nature"",""direction""=>""290"",""inf...",POINT (13.14605 52.39099)
1170653,13957201886,Referenzfläche,None,None,None,None,None,None,None,"""board_type""=>""nature"",""direction""=>""110"",""inf...",POINT (13.15621 52.39125)
1170659,13957278579,Waldpanorama,None,None,None,None,None,neighbourhood,None,None,POINT (13.48823 52.64395)
...,...,...,...,...,...,...,...,...,...,...,...
1171149,13964274255,Elektro-EU.DS GmbH,None,None,None,None,None,None,None,"""addr:city""=>""Berlin"",""addr:housenumber""=>""14""...",POINT (13.53569 52.43593)
1171160,13964943133,Peter Hellmich OHG,None,None,None,None,None,None,None,"""addr:city""=>""Berlin"",""addr:housenumber""=>""49""...",POINT (13.44016 52.51831)
1171162,13965106045,Elephant and Castle,None,None,None,None,None,None,None,"""addr:city""=>""Berlin"",""addr:housenumber""=>""19""...",POINT (13.42678 52.48911)
1171163,13965269664,Autoservice Mattha,None,None,None,None,None,None,None,"""addr:city""=>""Berlin"",""addr:housenumber""=>""60""...",POINT (13.43862 52.51917)
1171164,13965269665,Die Fußbodentherapeuten,None,None,None,None,None,None,None,"""addr:city""=>""Berlin"",""addr:housenumber""=>""60""...",POINT (13.4389 52.51935)

### DATA CLEANING

In [57]:
df

,osm_id,code,fclass,name,ref,oneway,maxspeed,layer,bridge,tunnel,geometry
0,4045150,5122,residential,Waldstraße,None,B,50,0,F,F,"LINESTRING (13.60932 52.37462, 13.60936 52.374..."
1,4045194,5122,residential,Ursula-Goetze-Straße,None,B,30,0,F,F,"LINESTRING (13.53136 52.49263, 13.53136 52.492..."
2,4045220,5122,residential,Hönower Straße,None,B,30,0,F,F,"LINESTRING (13.52667 52.48948, 13.52639 52.489..."
3,4045223,5122,residential,Gundelfinger Straße,None,F,30,0,F,F,"LINESTRING (13.52477 52.48558, 13.52484 52.485..."
4,4045243,5113,primary,Frankfurter Allee,B 1;B 5,F,50,0,F,F,"LINESTRING (13.4542 52.51571, 13.45431 52.5157..."
...,...,...,...,...,...,...,...,...,...,...,...
460166,1532222905,5155,steps,None,None,B,0,0,F,F,"LINESTRING (13.39468 52.52327, 13.39471 52.52327)"
460167,1532222906,5153,footway,None,None,B,0,0,F,F,"LINESTRING (13.39471 52.52327, 13.39475 52.52326)"
460168,1532281873,5153,footway,None,None,B,0,0,F,F,"LINESTRING (13.39692 52.38838, 13.39727 52.38838)"
460169,1532281874,5153,footway,None,None,B,0,0,F,F,"LINESTRING (13.39727 52.38838, 13.39789 52.388..."
460170,1532330714,5141,service,None,None,B,0,0,F,F,"LINESTRING (13.50351 52.635, 13.50306 52.63466..."